apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-fe
  template:
    metadata:
      labels:
        app: node-fe
    spec:
      containers:
      - name: frontend
        image: zakydockerized/zaky-repo:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
