apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-be
  template:
    metadata:
      labels:
        app: node-be
    spec:
      containers:
      - name: backend
        image: zakydockerized/zaky-repo:be
        imagePullPolicy: Always
        ports:
        - containerPort: 3030

